name: 'terraform-validate'
description: 'Validates Terraform'
inputs:
  working-directory:
    description: 'Directory containing the Terraform configuration'
    required: true
    default: 'terraform'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.working-directory }}
